### ISSUE TITLE
write formal spec YAML config for simple hierarchical taxonomy sheets

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#10]
First quick attempt (as pseudo JSON schema in YAML).  It strikes me that configuration via TSV would be easier.

```yaml
column_name: 
    type: string
    description:  > 
            Name of a column in the original spreadsheet/tsv.  
            Only name columns here that you can specify a type for in the column_type config, 
             all other columns will be preserved.
column_type:
  enum: 
     cluster_id
     cluster_name
     cell_set
rank:
   description: "Use this to number hierarchical cell sets, starting at 0 for cluster (leaf nodes)"
   type: number
 ```  
  

Questions:
* Do we also want the ability to preserve type in other fields (float vs string) ?
* Should we bundle this with requests for more general information about the taxonomy?  It would be good to at least have some link to the data.  Some other fields from the [CCN2 taxonomy metadata table ](https://github.com/brain-bican/CCN2/blob/main/doc/CCN2_table_doc.md#taxonomy-metadata-table) might be useful -although most should be superceded by fields coming from automated pipelines.  Alternatively, we could just have users fill these out in the tool.
