### ISSUE TITLE
Support comments on annotations.

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#113]
Planned CAS updates to support this are detailed in Option 1 here https://github.com/cellannotation/cell-annotation-schema/issues/100#issuecomment-1964287672

Proposal for UI:
 - Each row in the annotation table has a button for comments.  This opens a table with any existing comments to which users can add additional rows. Each row has the following columns.
 
```yaml
  time:  (autofilled)
  name: (autofilled)
  review: "String. Either “Agree” or “Disagree”. This records whether the user agreed or disagreed."
  explanation: "Free-text of the message explaining the reasoning why the user disagreed. If “Agree”, then put in NA."
```

Implementation:
In table - indicate whether comments are present and whether review is good or bad (green/red).  Should be at beginning of row.
In Edit view - display all reviews.
Add review button - pops up a review window.
